[global]
type=global
user_agent=Beraxis-AI-Asterisk
endpoint_identifier_order=username,ip,header,auth_username

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=109.199.109.53
external_media_address=109.199.109.53
local_net=127.0.0.1/32
local_net=172.16.0.0/12
local_net=192.168.0.0/16
local_net=10.0.0.0/8

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_signaling_address=109.199.109.53
external_media_address=109.199.109.53
local_net=127.0.0.1/32
local_net=172.16.0.0/12

#include pjsip_wizard.conf
#include pjsip_custom.conf
