[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[beraxis_user]
type=endpoint
context=default
disallow=all
allow=ulaw,alaw,gsm
auth=beraxis_user_auth
aors=beraxis_user_aor
rewrite_contact=yes
force_rport=yes
direct_media=no

[beraxis_user_auth]
type=auth
auth_type=password
password=beraxis_sip_pass
username=beraxis_user

[beraxis_user_aor]
type=aor
max_contacts=5
qualify_frequency=30
