[beraxis_user]
type=wizard
sends_auth=no
accepts_auth=yes
sends_registrations=no
accepts_registrations=yes
inbound_auth/username=beraxis_user
inbound_auth/password=beraxis_sip_pass
endpoint/context=default
endpoint/disallow=all
endpoint/allow=ulaw,alaw,gsm
endpoint/rewrite_contact=yes
endpoint/force_rport=yes
endpoint/direct_media=no
aor/max_contacts=5
aor/qualify_frequency=30
